---
language: python
python: "2.7"

addons:
  hosts:
    - webapp.com

env:
  - PLAYBOOK=playbook.yml

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y curl

install:
  # Install Ansible.
  - sudo pip install paramiko PyYAML jinja2 httplib2
  - sudo pip install ansible

before_script:
  - ln -s ansible-role-webapp ../mauricios.WebApp
  - sudo ln -s ansible-role-webapp/tests/webapp /var/www/webapp

script:
  - "cd tests"
  # Install dependencies
  - ansible-galaxy install -r dependencies.txt
  - ansible-playbook $PLAYBOOK --syntax-check
  - ansible-playbook $PLAYBOOK --connection=local
  - "ansible-playbook $PLAYBOOK --connection=local | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)"
  - mysql -V
  - apachectl -v
  - php -v
  - php -i | grep -q 'mysql' && (echo 'PHP MySQL installed' && exit 0) || (echo 'PHP MySQL not installed' && exit 1)
  - apachectl -M | grep -q 'php' && (echo 'PHP module for Apache installed' && exit 0) || (echo 'HP module for Apache not installed' && exit 1)
  - curl http://myapp.com


notification:
  email: false
