---
- debug:
    msg: "Installing app '{{ app_item.name }}'"
  tags: always

- name: Install app | Make sure the current directory of the webapp is present
  become: yes
  file:
    path: "{{ webapp.installation_path }}/{{ app_item.name }}/{{ webapp.release_dir }}"
    state: directory
    owner: "{{ ansible_user_id }}"

- name: Install app | Make sure the app symlink of the webapp is present
  file:
    src: "{{ webapp.release_dir }}"
    dest: "{{ webapp.installation_path }}/{{ app_item.name }}/current"
    state: link
    force: yes
  when: webapp.release_dir != ""

- name: "Install app | Add/Update webapp repo"
  git:
    repo: "{{ app_item.repo.url }}"
    dest: "{{ webapp.installation_path }}/{{ app_item.name }}/current"
    version: "{{ app_item.repo.version | default('master') }}"
    update: yes
    accept_hostkey: true
  when: app_item.repo.url is defined and app_item.repo.url != None
  tags: pull
