---
- name: Make sure the www directory is present
  sudo: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
  with_items:
    - "/var/www"

- name: Make sure the current directory of the webapp is present
  sudo: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  with_items:
    - "{{ webapp['base_symlink'] }}"
    - "/var/www/{{ webapp['name'] }}/releases/current"
  when: webapp['base_symlink'] is defined

- name: Make sure the app symlink of the webapp is present
  file:
    src: "releases/current"
    dest: "/var/www/{{ webapp['name'] }}/app"
    state: link
    force: yes
  when: webapp['base_symlink'] is defined

- name: Make sure the base symlink of the webapp is present
  file:
    src: "{{ webapp['base_symlink'] }}"
    dest: "/var/www/{{ webapp['name'] }}/base"
    state: link
    force: yes
  when: webapp['base_symlink'] is defined and webapp['base_symlink']

- name: "Add/Update webapp repo"
  git:
    repo: "{{ webapp['repo']['url'] }}"
    dest: "/var/www/{{ webapp['name'] }}/app"
    version: "{{ webapp['repo']['version'] }}"
    update: yes
    accept_hostkey: true
  when: webapp['repo'] is defined

- name: Ensure app directories exist
  file:
    path: "/var/www/{{ webapp['name'] }}/{{ item }}"
    state: directory
  with_items: webapp['app_dirs']

- name: Ensure webserver directories exist
  sudo: yes
  file:
    path: "/var/www/{{ webapp['name'] }}/{{ item }}"
    state: directory
    mode: 0777
    owner: "{{ apache['user'] }}"
    group: "{{ apache['user'] }}"
  with_items: webapp['webserver_dirs']

- name: Make sure the the ACLs directories are present
  file:
    path: "/var/www/{{ webapp['name'] }}/{{ item }}"
    state: directory
  with_items: webapp['ACL_dirs']

- name: Make sure the file system ACLs with default and webserver user are present
  acl:
     name: "/var/www/{{ webapp['name'] }}/{{ item }}"
     entity: "{{ apache['user'] }}"
     etype: user
     permissions: rxw
     default: yes
     state: present
  with_items: webapp["ACL_dirs"]

- name: Make sure the file system ACLs with current user are present
  acl:
     name: "/var/www/{{ webapp['name'] }}/{{ item }}"
     entity: "{{ ansible_user_id }}"
     etype: user
     permissions: rxw
     default: yes
     state: present
  with_items: webapp["ACL_dirs"]

- name: Create symlinks to base
  file:
    src: "{{ item.src }}"
    dest: "/var/www/{{ webapp['name'] }}/app/{{ item.dest }}"
    state: link
    force: yes
  with_items: webapp["links_to_base"]

- name: Create internal symlinks
  file:
    src: "{{ item.src }}"
    dest: "/var/www/{{ webapp['name'] }}/app/{{ item.dest }}"
    state: link
    force: yes
  with_items: webapp['internal_links']
