---
- debug: var=webapp verbosity=1
  tags: vars

- name: "Download Apps"
  include: app.yml
  with_items: "{{ webapp.apps | default([]) }}"
  loop_control:
    loop_var: app_item
  tags: apps

- name: Provision Apps
  include_role:
    name: Aplyca.AppProvision
  vars:
    app: "{{ item }}"
  with_items: "{{ webapp.apps | default([]) }}"
