---
- name: Make sure the installation path exists is present
  sudo: yes
  file:
    path: "{{ webapp['installation_path'] }}"
    state: directory
    mode: 0777
  when: webapp['installation_path'] is defined and webapp['installation_path'] != None

- name: Make sure the current directory of the webapp is present
  file:
    path: "{{ webapp['installation_path'] }}/{{ webapp['name'] }}/{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "releases/current"
  when: webapp['installation_path'] is defined and webapp['installation_path'] != None

- name: Make sure the app symlink of the webapp is present
  file:
    src: "releases/current"
    dest: "{{ webapp['installation_path'] }}/{{ webapp['name'] }}/app"
    state: link
    force: yes
  when: webapp['installation_path'] is defined and webapp['installation_path'] != None

- name: "Add/Update webapp repo"
  git:
    repo: "{{ webapp['repo']['url'] }}"
    dest: "{{ webapp['installation_path'] }}/{{ webapp['name'] }}/app"
    version: "{{ webapp['repo']['version'] | default('master') }}"
    update: yes
    accept_hostkey: true
  when: webapp['repo']['url'] is defined and webapp['repo']['url'] != null and webapp['installation_path'] is defined and webapp['installation_path'] != None

- name: Ensure app directories exist
  file:
    path: "{{ webapp['installation_path'] }}/{{ webapp['name'] }}/{{ item }}"
    state: directory
  with_items: webapp['app_dirs']

- name: Make sure the Storage directories are present
  file:
    path: "{{ item }}"
    state: directory
  with_items: webapp['storage']

- name: Make sure the storage ACLs with default and webserver user are present
  acl:
     name: "{{ item }}"
     entity: "{{ apache['user'] }}"
     etype: user
     permissions: rxw
     default: yes
     state: present
  with_items: webapp["storage"]

- name: Make sure the storage ACLs with current user are present
  acl:
     name: "{{ item }}"
     entity: "{{ ansible_user_id }}"
     etype: user
     permissions: rxw
     default: yes
     state: present
  with_items: webapp["storage"]

- name: Make sure the app directories with ACLs are present
  file:
    path: "{{ webapp['installation_path'] }}/{{ webapp['name'] }}/{{ item }}"
    state: directory
  with_items: webapp['ACL_dirs']

- name: Make sure the ACLs for app directories with default and webserver user are present
  acl:
     name: "{{ webapp['installation_path'] }}/{{ webapp['name'] }}/{{ item }}"
     entity: "{{ apache['user'] }}"
     etype: user
     permissions: rxw
     default: yes
     state: present
  with_items: webapp["ACL_dirs"]

- name: Make sure the ACLs for app directories with current user are present
  acl:
     name: "{{ webapp['installation_path'] }}/{{ webapp['name'] }}/{{ item }}"
     entity: "{{ ansible_user_id }}"
     etype: user
     permissions: rxw
     default: yes
     state: present
  with_items: webapp["ACL_dirs"]

- name: Create symlinks to storage
  file:
    src: "{{ item.src }}"
    dest: "{{ webapp['installation_path'] }}/{{ webapp['name'] }}/app/{{ item.dest }}"
    state: link
    force: yes
  with_items: webapp["links_to_storage"]

- name: Create internal symlinks
  file:
    src: "{{ item.src }}"
    dest: "{{ webapp['installation_path'] }}/{{ webapp['name'] }}/app/{{ item.dest }}"
    state: link
    force: yes
  with_items: webapp['internal_links']
