---
- name: Make sure the live directory of the webapp is present
  sudo: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
  with_items:
    - /var/www
    - /mnt/storage/www

- name: Make sure the current directory of the webapp is present
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "/mnt/storage/www/{{ webapp['name'] | lower }}"
    - "/var/www/{{ webapp['name'] | lower }}/current"

- name: Make sure the base symlink of the webapp is present
  file:
    src: "/mnt/storage/www/{{ webapp['name'] | lower }}"
    dest: "/var/www/{{ webapp['name'] | lower }}/base"
    state: link
    force: yes

- name: Make sure the app symlink of the webapp is present
  file:
    src: "current"
    dest: "/var/www/{{ webapp['name'] | lower }}/app"
    state: link

- name: "Add/Update webapp repo, using {{ webapp['repo']['version'] }}"
  git:
    repo: "{{ webapp['repo']['server'] }}:{{ webapp['repo']['url'] }}"
    dest: "/var/www/{{ webapp['name'] | lower }}/app"
    version: "{{ webapp['repo']['version'] }}"
    update: no
    accept_hostkey: true
  tags:
    - release

- name: Sync files from base to current
  shell: "rsync -azu --exclude '/var' app/ base/"
  args:
    chdir: "/var/www/{{ webapp['name'] | lower }}"
  ignore_errors: yes
  changed_when: False


